# Welcome to Colab!

In [1]:
from google.colab import files
uploaded=files.upload()

Saving diabetes.csv to diabetes.csv


In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [3]:
df=pd.read_csv("diabetes.csv")

In [4]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [5]:
df.shape

(768, 9)

In [6]:
df.isnull().sum()

,0
Pregnancies,0
Glucose,0
BloodPressure,0
SkinThickness,0
Insulin,0
BMI,0
DiabetesPedigreeFunction,0
Age,0
Outcome,0


In [7]:
X=df.drop("Outcome",axis=1)
y=df["Outcome"]

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
lr_model=LogisticRegression()
lr_model.fit(X_train,y_train)
lr_pred=lr_model.predict(X_test)

In [11]:
lr_pred=lr_model.predict(X_test)

In [12]:
print('Accuracy:', accuracy_score(y_test, lr_pred))

Accuracy: 0.7532467532467533


In [13]:
print('Confusion Matrix:\n', confusion_matrix(y_test, lr_pred))

Confusion Matrix:
 [[79 20]
 [18 37]]


In [14]:
print('Classification Report:\n', classification_report(y_test, lr_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.80      0.81        99
           1       0.65      0.67      0.66        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154



In [15]:
dt_model=DecisionTreeClassifier()
dt_model.fit(X_train,y_train)
dt_pred=dt_model.predict(X_test)

In [16]:
dt_pred = dt_model.predict(X_test)

In [17]:
print('Accuracy:', accuracy_score(y_test, lr_pred))

Accuracy: 0.7532467532467533


In [18]:
print('Confusion Matrix:\n', confusion_matrix(y_test, lr_pred))

Confusion Matrix:
 [[79 20]
 [18 37]]


In [19]:
print('Classification Report:\n', classification_report(y_test, lr_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.80      0.81        99
           1       0.65      0.67      0.66        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154



In [20]:
rf_model=RandomForestClassifier()
rf_model.fit(X_train,y_train)
rf_pred=rf_model.predict(X_test)

In [21]:
rf_pred = rf_model.predict(X_test)

In [22]:
print('Accuracy:', accuracy_score(y_test, rf_pred))

Accuracy: 0.7337662337662337


In [23]:
print('Confusion Matrix:\n', confusion_matrix(y_test, rf_pred))

Confusion Matrix:
 [[78 21]
 [20 35]]


In [24]:
print('Classification Report:\n', classification_report(y_test, rf_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.79      0.79        99
           1       0.62      0.64      0.63        55

    accuracy                           0.73       154
   macro avg       0.71      0.71      0.71       154
weighted avg       0.73      0.73      0.73       154



In [25]:
lr_acc = accuracy_score(y_test, lr_pred)
dt_acc = accuracy_score(y_test, dt_pred)
rf_acc = accuracy_score(y_test, rf_pred)

comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'Decision Tree', 'Random Forest'],
    'Accuracy': [lr_acc, dt_acc, rf_acc]
})

comparison = comparison.sort_values('Accuracy', ascending=False).reset_index(drop=True)
comparison

,Model,Accuracy
0,Decision Tree,0.779221
1,Logistic Regression,0.753247
2,Random Forest,0.733766
